@campaign_id=

// Get all posts by campaign_id
GET https://www.patreon.com/api/posts
?filter[campaign_id]={{campaign_id}}
# &filter[tag]=user_tag_1,user_tag_2
&fields[post]=content,created_at,published_at,title,url,teaser_text,image,thumbnail,thumbnail_url
&fields[user]=full_name,url
&fields[post_tag]=tag_type,value
&filter[is_draft]=false
&filter[is_public]=false
&include=campaign,user_defined_tags
&sort=-published_at
&json-api-version=1.0
Accept-Encoding: gzip, deflate, br, zstd
Accept: application/json